version: "3.9"  # optional since v1.27.0
services:
  ros:
    image: zhuoqiw/sunny-tis:latest
    command: ros2 launch pipeline_tis main.launch.py
    container_name: ros
    privileged: true
    network_mode: "host"
    restart: on-failure

