version: "3.9"  # optional since v1.27.0
services:
  ros:
    image: zhuoqiw/sunny-tis:latest
    entrypoint: /ws/ros_entrypoint.sh
    command: ros2 launch pipeline_tis main.launch.py
    container_name: ros
    network_mode: "host"
    restart: on-failure
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/gpiochip0:/dev/gpiochip0"

