version: "3.9"  # optional since v1.27.0
services:
  ros:
    image: zhuoqiw/sunny-tis:deploy
    command: ros2 launch pipeline_tis main.launch.py
    container_name: ros
    network_mode: "host"
    restart: on-failure
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
      - ros2_log:/root/.ros/log
      - seam_tracking:/workspace/sunny/install/seam_tracking/lib/python3.8/site-packages/seam_tracking

volumes:
  ros2_log:
  seam_tracking:
