int64 index     # indicate the index of code list
---
string code     # python code
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages
