camera_tis_node:
  ros__parameters:
    exposure_time: 1000         # int, exposure time in microseconds
    width: 1536                 # int, width in pixel
    height: 1024                # int, height in pixel
