laser_line_filter_node:
  ros__parameters:
    enable: false               # bool, enable
    window_size: 10             # int pixel
    gap: 5                      # int pixel
    deviate: 5.                 # float pixel
    step: 2.                    # float pixel
    length: 30                  # int pixel
